<?php /** 
* Moogento
* 
* SOFTWARE LICENSE
* 
* This source file is covered by the Moogento End User License Agreement
* that is bundled with this extension in the file License.html
* It is also available online here:
* http://www.moogento.com/License.html
* 
* NOTICE
* 
* If you customize this file please remember that it will be overwrtitten
* with any future upgrade installs. 
* If you'd like to add a feature which is not in this software, get in touch
* at www.moogento.com for a quote.
* 
* ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
* File        hint.phtml
* @category   Moogento
* @package    noMoreSpam
* @copyright  Copyright (c) 2014 Moogento <info@moogento.com> / All rights reserved.
* @license    http://www.moogento.com/License.html
*/ ?>
<div class="moogento-notice">
	<div class="floatingcows">
		<div class="floatingsheep" style="background-image:url(http://www.moogento.com/logo/moogento_logo_nomorespam<?php echo $this->getMooo(); ?>.png);"><a href="http://www.moogento.com" id="mooink">&nbsp;</a></div> 
	    <div id="mooinfo">
			<h4>
	        <?php echo $this->__('<a target="_blank" href="http://www.moogento.com/nomorespam">noMoreSpam</a>'); ?>
	    	</h4>
			<? echo $this->getInfoHtml(); ?>
		</div>
	</div>
	<ul id="wikilinks">
		<li><a class="wiki" href="http://www.moogento.com/wiki/noMoreSpam_Quickstart"><span>★</span> noMoreSpam Wiki</a></li>
		<li><a class="store" href="http://www.moogento.com"><img src="http://www.moogento.com/images/moogento-favicon_32x32.png" width=16 /> Moogento Store</a></li>
	</ul>
</div>
<div style="clear:both;" />